#!/bin/sh -e
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
mkdir 0
runApplication setVelocityField -time 0
runApplication setTracerRatios
runApplication advectTracerRatiosFoam
runApplication gmtFoam T
runApplication gmtFoam q
time=200
#runApplication sumFields $time Tsum $time T1 $time T2
#runApplication sumFields $time Tdiff $time Tsum $time T -scale0 1 -scale1 -1
#runApplication gmtFoam -time $time Tdiff

# ------------------- end-of-file
