#!/bin/sh -e
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication add2dMountain
runApplication setVelocityField
cp init0/T 0
runApplication setScalarOverOrography
runApplication advectionFoam
runApplication gmtFoam -time 5000 T
evince 5000/T.pdf &
# ----------------------------------------------------------------- end-of-file
