#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf *00/
rm -rf 0/
rm -rf log.*
cleanCase

# ----------------------------------------------------------------- end-of-file
