#!/bin/sh -e
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
mkdir 0
runApplication setVelocityField -time 0
runApplication setTwoInitialTracerFields
runApplication advectTwoTracersFoam
runApplication gmtFoam T1
runApplication gmtFoam T2
# ----------------------------------------------------------------- end-of-file
