#!/bin/sh -e
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#Clean test case directory.
./Allclean

#Create mesh and fields.
runApplication blockMesh
mkdir 0
runApplication setVelocityField -time 0
runApplication setMoistureVariables

#Evolve the system.
runApplication advectMoistureFoam

#Diagnostics
runApplication gmtFoam rt -time 1

echo "\nTest case example has been successfully completed. \n"


# ------------------- end-of-file
