#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wmake $makeType prescribedFields
wmake $makeType finiteVolume
wmake $makeType functionObjects/field
wmake $makeType functionObjects/solvers
