#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -e

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

wmake $makeType ExnerTheta
wmake $makeType shallowWater
wmake $makeType thermalFields
wmake $makeType TurbulenceModels
wmake $makeType finiteVolume
wmake $makeType HodgeOps
wmake $makeType sampling
wmake $makeType prescribedFields
wmake $makeType orography
wmake $makeType ghostMesh

